# NumPy Array Math Wizard

In [34]:
import numpy as np
from sklearn.linear_model import MultiTaskElasticNet

arr = np.array([[1,2,3],[4,5,6]] )
arr1 = np.array([10,20,30])

# Addition
add = arr + arr1
print(add)

print("-"  *60)
# Subtraction

sub = arr - arr1
print(sub)

print("-"  *60)
# Multiplication 
multi = arr*arr1
print(multi)

print("-"  *60)
# Division
DIV = arr%arr1
print(DIV)

print("-"  *60)
# convert arr in float using typecasting function
print(arr.astype(float))


[[11 22 33]
 [14 25 36]]
------------------------------------------------------------
[[ -9 -18 -27]
 [ -6 -15 -24]]
------------------------------------------------------------
[[ 10  40  90]
 [ 40 100 180]]
------------------------------------------------------------
[[1 2 3]
 [4 5 6]]
------------------------------------------------------------
[[1. 2. 3.]
 [4. 5. 6.]]


In [14]:
arr2 = np.array([1,4,9,16,25])

# square root function
print(np.sqrt(arr2))

print("-----------")
# Exponentia;l function
print(np.exp(arr2))

print("-----------")
# Sin function
print(np.sin(arr2))

[1. 2. 3. 4. 5.]
-----------
[2.71828183e+00 5.45981500e+01 8.10308393e+03 8.88611052e+06
 7.20048993e+10]
-----------
[ 0.84147098 -0.7568025   0.41211849 -0.28790332 -0.13235175]


In [ ]:
arr3 = np.array( [[5,12,3],[8,2,7]])

# Sum of all elements
print(arr3.sum())

# Find max in each column
print(np.max(arr3 , axis=0))

# Find min in each row
print(np.min(arr3 , axis=1))



37
[ 8 12  7]
[3 2]
[[1. 2. 3.]
 [4. 5. 6.]]
