# NumPy Array Explorer

In [2]:
import numpy as np

arr = np.array([2,4,6,8,10,12,14,16,18,20])

print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.ndim)
print(arr.reshape(2,5))
print(arr.argmax())
print(arr.max())
print(arr.min())
print(arr[5])




(10,)
int64
10
1
[[ 2  4  6  8 10]
 [12 14 16 18 20]]
9
20
2
12


In [6]:
arr1 = np.zeros([3,3])
arr2 = np.random.randint(1 , 101 , 20)
arr3 = np.linspace(0 , 5 , 10)

print(arr1)
print("-" *60)
print(arr2)
print("-" *60)
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
------------------------------------------------------------
[ 89  59  58  64  96  34  95   9 100   6  17  14  91  27  91  90  14  60
  32  40]
------------------------------------------------------------
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [ ]:
arr4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr4)

print(arr4[0:1,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[2]
